### ISSUE TITLE
Spawn Manager Enhancements

### ISSUE THREAD

**Issue by Justuna** [Justuna/CogschanGame#100]
- Right now, the focal point for spawning for each manager is based on the spawn manager, but the radius around that point is based on the actual spawner, which lumps together multiple spawn managers that otherwise have different purposes and intended behaviors. It would be nice to have both the radius and focal point be inherent to the spawn manager to allow for better fine-tuning.
- Since the level is a large area and does not have an obvious "spawn area," it would be nice to create a separate spawn manager that picks random points in a box volume, rather than points in a disc, for more uniform spawning.

**Comment by kitkat-001** [comment]
the branch is named wrong, dwai
