### ISSUE TITLE
Fall Damage 🌠

### ISSUE THREAD

**Issue by Justuna** [Justuna/CogschanGame#58]
Right now, there is no penalty for falling from a really high height. Add a script/function that automatically damages Cogschan if she hits the ground above a certain velocity (scaling with extra velocity).

**Comment by kitkat-001** [comment]
Should this apply to just Cogschan or enemies as well?

**Comment by kitkat-001** [comment]
gonna do it for all grounded enemies as well as the player

**Comment by Justuna** [comment]
It's fine if fall damage can be cancelled by the dash, because in-game it will be on cooldown for a lot longer so it's more of a strategic choice when to use it

Also most dash abilities in Risk of Rain work the same way, which is what we're pulling from for a lot of our game
