### ISSUE TITLE
Catch Falling Cogschan 🥅

### ISSUE THREAD

**Issue by Justuna** [Justuna/CogschanGame#61]
Implement some sort of system (maybe using the interactable) that will sit in the void under levels and teleport Cogschan back onto the stage when she falls off. This could possibly also be paired with a "last touched ground" position property on Cogschan somewhere, so that she can be teleported back to the last place she fell from. 

Additionally, her velocity should be maintained (mostly so that she will still take damage upon landing as a penalty for falling off).

**Comment by kitkat-001** [comment]
on it

**Comment by kitkat-001** [comment]
don't merge yet, I wanna add smth
